services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: german_words
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d german_words"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network
      
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/german_words
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Доступ с хоста
    expose:
      - "3000"       # Доступ внутри Docker-сети
    environment:
      - CHOKIDAR_USEPOLLING=true  # Для hot-reload в Docker
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src    # Для live-обновлений
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    name: german-words-network
    driver: bridge